namespacecreate: "false"
namespace: "empty"
replicas: 1
deployment:
  name: "empty"
  image:
    repository: "empty"
    name: "empty"
    tag: "empty"
hpa:
  min: 1
  max: 50
  averageUtilization: 50
service:
  port: 80
  targetPort: 3000
containers:
  port: 3000
resources:
  cpu: "100m"
  memory: "100Mi"
ingress:
  class: nginx
  domain: "dev.teknodice.com"
  active: false
mysqlconfig:
  MYSQL_USERNAME: "root"
  MYSQL_PASSWORD_SECRET_NAME: "devmysql"
  MYSQL_PASSWORD_SECRET_KEY: "mysql-root-password"
  MYSQL_INSTANCE_NAME: "my_database"
  MYSQL_PORT_3306_TCP_ADDR: "mysqldev.dev.svc.cluster.local"
  MYSQL_PORT_3306_TCP_PORT: 3306